// Copyright (C) 2026 longtimeno-c
// SPDX-License-Identifier: GPL-3.0-or-later
#include "addons/ai/vocabulary.h"

namespace mv::ai {
namespace {
// Everyday things a camera roll holds: people, animals, vehicles, places,
// scenes, objects, food, events, activities, text and screens. Not tuned to
// the COCO eval set (issue #85): only broad, and the near-synonyms a query
// can lose to ("dog playing" under "a dog") are why a row may trail eight.
constexpr std::string_view kLabels[] = {
    "person", "man", "woman", "child", "baby", "boy", "girl", "group of people", "crowd", "family", "couple",
    "friends", "selfie", "portrait", "face", "hands", "feet", "dog", "puppy", "cat", "kitten", "bird",
    "horse", "cow", "sheep", "goat", "pig", "chicken", "duck", "fish", "insect", "butterfly", "bee", "spider",
    "snake", "lizard", "frog", "turtle", "rabbit", "squirrel", "deer", "bear", "elephant", "giraffe", "zebra",
    "lion", "tiger", "monkey", "whale", "dolphin", "seal", "penguin", "owl", "parrot", "swan", "seagull",
    "pigeon", "car", "truck", "bus", "motorcycle", "bicycle", "scooter", "train", "tram", "subway",
    "airplane", "helicopter", "boat", "ship", "sailboat", "kayak", "canoe", "tractor", "taxi", "van",
    "ambulance", "fire truck", "police car", "traffic", "road", "street", "highway", "bridge", "tunnel",
    "parking lot", "gas station", "traffic light", "street sign", "stop sign", "crosswalk", "sidewalk",
    "city", "skyline", "skyscraper", "building", "house", "apartment", "church", "cathedral", "mosque",
    "temple", "castle", "tower", "lighthouse", "windmill", "barn", "farm", "village", "town square", "market",
    "shop", "store", "supermarket", "restaurant", "cafe", "bar", "pub", "hotel", "office", "school",
    "classroom", "library", "museum", "art gallery", "hospital", "airport", "train station", "stadium",
    "concert", "theater", "cinema", "park", "playground", "garden", "backyard", "field", "meadow", "forest",
    "jungle", "woods", "tree", "flower", "rose", "tulip", "sunflower", "grass", "leaves", "autumn leaves",
    "mountain", "hill", "valley", "cliff", "rock", "cave", "canyon", "desert", "sand dune", "volcano",
    "glacier", "iceberg", "snow", "ice", "waterfall", "river", "stream", "lake", "pond", "sea", "ocean",
    "beach", "coast", "island", "harbor", "pier", "waves", "sky", "clouds", "sunset", "sunrise", "night sky",
    "stars", "moon", "sun", "rain", "storm", "lightning", "fog", "rainbow", "landscape", "cityscape",
    "aerial view", "indoor", "outdoor", "room", "living room", "bedroom", "kitchen", "bathroom",
    "dining room", "hallway", "staircase", "window", "door", "wall", "floor", "ceiling", "roof", "balcony",
    "garage", "basement", "attic", "pool", "swimming pool", "hot tub", "fireplace", "sofa", "chair", "table",
    "desk", "bed", "lamp", "mirror", "curtains", "carpet", "shelf", "bookshelf", "cabinet", "television",
    "computer", "laptop", "keyboard", "mouse", "monitor", "phone", "smartphone", "tablet", "camera",
    "headphones", "speaker", "remote control", "clock", "watch", "book", "newspaper", "magazine", "document",
    "paper", "receipt", "letter", "envelope", "notebook", "pen", "pencil", "screenshot", "text", "sign",
    "poster", "map", "chart", "diagram", "whiteboard", "blackboard", "drawing", "painting", "sculpture",
    "statue", "graffiti", "mural", "photograph", "picture frame", "logo", "barcode", "qr code", "numbers",
    "calendar", "ticket", "money", "coins", "credit card", "passport", "key", "lock", "bag", "backpack",
    "suitcase", "handbag", "wallet", "umbrella", "hat", "cap", "glasses", "sunglasses", "shoes", "boots",
    "sneakers", "shirt", "t-shirt", "dress", "jacket", "coat", "jeans", "suit", "tie", "scarf", "gloves",
    "jewelry", "ring", "necklace", "earrings", "toy", "teddy bear", "doll", "lego", "ball", "balloon", "kite",
    "game", "board game", "video game", "cards", "dice", "puzzle", "guitar", "piano", "drums", "violin",
    "microphone", "musical instrument", "bottle", "wine", "beer", "cocktail", "coffee", "tea", "cup", "mug",
    "glass", "plate", "bowl", "fork", "knife", "spoon", "chopsticks", "food", "meal", "breakfast", "lunch",
    "dinner", "dessert", "cake", "birthday cake", "cupcake", "cookie", "bread", "sandwich", "burger", "pizza",
    "pasta", "noodles", "rice", "sushi", "salad", "soup", "steak", "chicken dish", "seafood", "fruit",
    "apple", "banana", "orange", "strawberry", "grapes", "lemon", "watermelon", "vegetables", "carrot",
    "broccoli", "tomato", "potato", "corn", "cheese", "eggs", "ice cream", "chocolate", "candy", "snack",
    "drink", "juice", "water", "milk", "fridge", "oven", "microwave", "stove", "sink", "toilet", "shower",
    "bathtub", "towel", "toothbrush", "plant", "potted plant", "cactus", "vase", "candle", "christmas tree",
    "decorations", "fireworks", "party", "wedding", "birthday party", "celebration", "festival", "parade",
    "graduation", "holiday", "vacation", "travel", "hiking", "camping", "tent", "campfire", "fishing",
    "swimming", "surfing", "skiing", "snowboarding", "skateboarding", "cycling", "running", "football",
    "soccer", "basketball", "baseball", "tennis", "golf", "volleyball", "hockey", "boxing", "yoga", "gym",
    "dancing", "singing", "cooking", "eating", "reading", "writing", "working", "sleeping", "playing",
    "laughing", "smiling", "hugging", "kissing", "walking", "sitting", "standing", "tools", "hammer",
    "screwdriver", "ladder", "construction", "construction site", "crane", "machine", "factory", "engine",
    "wheel", "tire", "cable", "wires", "electronics", "circuit board", "battery", "charger", "light",
    "light bulb", "neon lights", "street light", "lantern", "shadow", "reflection", "silhouette", "close-up",
    "macro", "blur", "abstract", "pattern", "texture", "wood", "metal", "stone", "brick", "concrete",
    "glass window", "fabric", "paper texture", "plastic", "water surface", "fire", "smoke", "dust", "sparks",
    "darkness", "black", "white", "red", "blue", "green", "yellow", "colorful", "black and white photo",
    "vintage photo", "x-ray", "medical scan", "microscope", "laboratory", "science", "space", "planet",
    "satellite", "rocket", "robot", "drone", "weapon", "gun", "sword", "armor", "soldier", "police",
    "firefighter", "doctor", "nurse", "chef", "teacher", "student", "worker", "farmer", "athlete", "musician",
    "artist", "tourist", "crowd at a concert", "audience", "queue", "meeting", "presentation", "conference",
    "classroom lecture", "church service", "funeral", "baby shower", "newborn", "toddler", "teenager",
    "elderly person", "grandparents", "pregnant woman", "bride", "groom", "mother and child",
    "father and son", "pet", "aquarium", "zoo", "farm animals", "wildlife", "nest", "eggs in a nest",
    "feather", "bone", "skull", "fossil", "dinosaur", "statue of liberty", "eiffel tower", "monument",
    "ruins", "old building", "modern architecture", "interior design", "furniture", "home", "yard", "fence",
    "gate", "mailbox", "driveway", "porch", "patio", "deck", "swing", "slide", "trampoline", "sandbox",
    "beach umbrella", "sunbathing", "sandcastle", "shells", "coral reef", "underwater", "scuba diving",
    "snorkeling", "lake house", "cabin", "mountain cabin", "ski resort", "snowman", "sled", "ice skating",
    "frozen lake", "rainy street", "wet road", "puddle", "flood", "drought", "field of wheat", "vineyard",
    "orchard", "greenhouse", "harvest", "hay bales", "cattle", "horse riding", "dog walking", "cat sleeping",
    "dog playing", "bird flying", "fish swimming", "car interior", "dashboard", "steering wheel", "cockpit",
    "airplane window", "airport terminal", "luggage", "hotel room", "bed and breakfast", "street food",
    "food truck", "farmers market", "grocery store", "shopping mall", "clothing store", "bookstore", "bakery",
    "butcher", "pharmacy", "bank", "atm", "post office", "police station", "fire station", "courthouse",
    "city hall", "parliament", "palace", "fountain", "plaza", "alley", "bridge over river", "canal", "dam",
    "harbor with boats", "marina", "yacht", "cruise ship", "ferry", "container ship", "port", "docks",
    "railway", "railroad tracks", "train platform", "bus stop", "bicycle lane", "parking garage",
    "electric scooter", "motorbike", "race car", "sports car", "vintage car", "pickup truck", "bulldozer",
    "excavator", "forklift", "airplane wing", "jet engine", "hot air balloon", "parachute", "paraglider",
    "climbing", "rock climbing", "bouldering", "kayaking", "rowing", "sailing", "windsurfing", "kitesurfing",
    "wakeboarding", "jet ski", "motorboat", "water ski", "fishing boat",
};
}  // namespace

std::span<const std::string_view> labels() noexcept { return kLabels; }

}  // namespace mv::ai
