// SPDX-License-Identifier: GPL-2.0-or-later
// AppKit host for the Metal present lab. PR 16/17 built the canvas; PR 18
// adds the SwiftUI command bar hosted alongside it (plan/10, plan/15 —
// "the canvas is not ported to SwiftUI"). MvMetalView keeps covering the
// whole content view, exactly as PR 16/17 built it; the command bar is a
// sibling NSView drawn on top of its own top strip, the same "swapchain
// spans the client area, chrome is composited over it" shape the Windows
// DComp islands use — not a resize of the Metal view.
#import <AppKit/AppKit.h>
#import <Metal/Metal.h>
#import <QuartzCore/CAMetalLayer.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "core/job_system.h"
#include "core/trace.h"
#include "io/dir.h"
#include "shell/browse_index.h"
#include "shell/folder_model_mac.h"
#include "shell/input_state.h"
#include "shell/present_lab_mac.h"

// Generated by swiftc -emit-objc-header from src.swift/MediaViewerChrome
// (cmake/darwin.cmake builds that target before this file, and adds its
// output directory to the include path). Declares `MVChromeHost` /
// `+makeCommandBarView`, the one thing this file needs from Swift — see
// src.swift/MediaViewerChrome/Sources/MediaViewerChrome/ChromeHost.swift.
#import "MediaViewerChrome-Swift.h"

namespace {
// Bridge target for mv_chrome_fit()/mv_chrome_one_to_one() (declared in
// src.swift/MediaViewerChrome/Sources/MVChromeBridge, called from
// CommandBarView.swift). Set once in -applicationDidFinishLaunching:, same
// lifetime as the window; the lab and its snapshot outlive the app delegate
// only because both are ivars of the single MvLabApp instance that owns this
// process's only window (plan/14-abi.md's shape, scoped to the lab).
mv::shell::input_snapshot* g_chrome_snap = nullptr;
mv::shell::present_lab_mac* g_chrome_lab = nullptr;
}  // namespace

// [any-thread] SwiftUI runs button actions on the main actor, so these run
// on the main thread in practice; they only ever touch input_snapshot the
// same way MvMetalView's event handlers do (edge-triggered counter bump,
// then wake), so there is nothing here that requires it.
extern "C" void mv_chrome_fit(void) {
  if (!g_chrome_snap) return;
  ++g_chrome_snap->fit_seq;
  // publish(), not just wake(): input_snapshot flows through a triple-buffer
  // publish_slot (core/spsc_ring.h) — the render thread only sees this bump
  // once publish() copies the snapshot in, same as every MvMetalView handler.
  if (g_chrome_lab) g_chrome_lab->publish(*g_chrome_snap);
  if (g_chrome_lab) g_chrome_lab->wake();
}
extern "C" void mv_chrome_one_to_one(void) {
  if (!g_chrome_snap) return;
  ++g_chrome_snap->one_to_one_seq;
  if (g_chrome_lab) g_chrome_lab->publish(*g_chrome_snap);
  if (g_chrome_lab) g_chrome_lab->wake();
}

// Command-bar strip height, in points (converted to backing pixels via the
// window's backingScaleFactor before it reaches input_snapshot.chrome_height_px
// — that field, and every canvas-rect field alongside it, is already in
// physical pixels, matching Windows' PerMonitorV2 convention).
constexpr CGFloat kChromeBarHeightPoints = 44.0;

// Declared in full (not just `@class`) because MvMetalView's own methods,
// defined below, send it messages (navigatePrev etc.) -- a bare forward
// declaration only lets the compiler know the type exists, not what it
// responds to. The @implementation stays further down, after MvMetalView's,
// so the file still reads outside-in (canvas, then chrome/app).
@class MvMetalView;
@interface MvLabApp : NSObject <NSApplicationDelegate, NSWindowDelegate>
@property(nonatomic, strong) NSWindow* window;
@property(nonatomic, strong) MvMetalView* view;
@property(nonatomic, strong) NSView* commandBar;

// plan/16-commands.md "Opening (argv, drop, PR 6)": the first entry that
// exists wins -- a folder opens that folder, a file opens its folder with
// that file selected. Used by argv parsing (main(), below) and
// -[MvMetalView performDragOperation:]. Returns NO (and the caller beeps)
// when nothing at `utf8_path` exists.
- (BOOL)openEntryPath:(const char*)utf8_path;
- (BOOL)hasFolder;
- (void)navigateNext;
- (void)navigatePrev;
- (void)navigateFirst;
- (void)navigateLast;
- (void)navigateSkip:(std::ptrdiff_t)delta;
@end

@interface MvMetalView : NSView
@property(nonatomic, assign) mv::shell::present_lab_mac* lab;
@property(nonatomic, assign) mv::shell::input_snapshot* snap;
// Weak-by-convention (assign, not strong): MvLabApp owns this view for its
// whole lifetime, the reverse is never true. Used for the browse commands
// (arrows, Home/End/PageUp/PageDown, Space/Backspace once a folder is open)
// that need folder_model/browse_index state MvLabApp owns, not just an
// input_snapshot bump like every other key here.
@property(nonatomic, assign) MvLabApp* app;
@end

@implementation MvMetalView
- (BOOL)wantsLayer {
  return YES;
}
- (CALayer*)makeBackingLayer {
  CAMetalLayer* layer = [CAMetalLayer layer];
  layer.pixelFormat = MTLPixelFormatBGRA8Unorm_sRGB;
  layer.framebufferOnly = YES;
  layer.maximumDrawableCount = 1;
  layer.displaySyncEnabled = YES;
  return layer;
}
- (BOOL)acceptsFirstResponder {
  return YES;
}
- (BOOL)isOpaque {
  return YES;
}

- (void)publish {
  if (self.lab && self.snap) self.lab->publish(*self.snap);
}

- (void)syncSize {
  const NSSize backing = [self convertSizeToBacking:self.bounds.size];
  self.snap->width = static_cast<std::uint32_t>(std::max(1.0, backing.width));
  self.snap->height = static_cast<std::uint32_t>(std::max(1.0, backing.height));
  self.snap->dpi_scale = static_cast<float>(self.window.backingScaleFactor);
  self.snap->chrome_height_px = static_cast<std::uint32_t>(
      kChromeBarHeightPoints * self.window.backingScaleFactor);
  ++self.snap->resize_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}

- (void)viewDidMoveToWindow {
  [super viewDidMoveToWindow];
  [self registerForDraggedTypes:@[ NSPasteboardTypeFileURL ]];
  [self syncSize];
}

// plan/16-commands.md "Opening (argv, drop, PR 6)": accept the drop as long
// as it names at least one file: URL, so -performDragOperation: can apply
// the same "first folder wins, else the first file's folder" rule -openEntryPath:
// already implements for argv. Any other pasteboard content (text, images
// dragged from a browser) is not a file and is refused.
- (NSDragOperation)draggingEntered:(id<NSDraggingInfo>)sender {
  NSArray<NSURL*>* urls = [sender.draggingPasteboard readObjectsForClasses:@[ NSURL.class ]
                                                                    options:nil];
  return urls.count > 0 ? NSDragOperationCopy : NSDragOperationNone;
}
- (NSDragOperation)draggingUpdated:(id<NSDraggingInfo>)sender {
  return [self draggingEntered:sender];
}
- (BOOL)performDragOperation:(id<NSDraggingInfo>)sender {
  NSArray<NSURL*>* urls = [sender.draggingPasteboard readObjectsForClasses:@[ NSURL.class ]
                                                                    options:nil];
  NSString* first = urls.firstObject.path;
  if (!first || !self.app) return NO;
  const bool opened = [self.app openEntryPath:first.UTF8String];
  if (!opened) NSBeep();
  return opened ? YES : NO;
}

- (void)setFrameSize:(NSSize)newSize {
  [super setFrameSize:newSize];
  [self syncSize];
}

- (void)viewDidChangeBackingProperties {
  [super viewDidChangeBackingProperties];
  ++self.snap->display_change_seq;
  [self syncSize];
}

- (void)mouseDown:(NSEvent*)event {
  (void)event;
  self.snap->mouse_down[0] = true;
  ++self.snap->activity_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}
- (void)mouseUp:(NSEvent*)event {
  (void)event;
  self.snap->mouse_down[0] = false;
  ++self.snap->activity_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}
- (void)rightMouseDown:(NSEvent*)event {
  (void)event;
  self.snap->mouse_down[1] = true;
  ++self.snap->activity_seq;
  [self publish];
}
- (void)rightMouseUp:(NSEvent*)event {
  (void)event;
  self.snap->mouse_down[1] = false;
  [self publish];
}
- (void)scrollWheel:(NSEvent*)event {
  self.snap->wheel_total += static_cast<std::int64_t>(event.scrollingDeltaY * 120.0);
  ++self.snap->activity_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}
- (void)mouseMoved:(NSEvent*)event {
  const NSPoint p = [self convertPoint:event.locationInWindow fromView:nil];
  const NSPoint backing = [self convertPointToBacking:p];
  self.snap->mouse_x = static_cast<float>(backing.x);
  self.snap->mouse_y = static_cast<float>(self.snap->height) - static_cast<float>(backing.y);
  self.snap->mouse_in_client = NSPointInRect(p, self.bounds);
  [self publish];
}
- (void)mouseDragged:(NSEvent*)event {
  [self mouseMoved:event];
  ++self.snap->activity_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}
- (void)keyDown:(NSEvent*)event {
  const NSString* chars = event.charactersIgnoringModifiers;
  const unichar c = chars.length > 0 ? [chars characterAtIndex:0] : 0;

  // plan/16-commands.md Browse table: <-/-> or A/D previous/next in every
  // mode; Home/End first/last; PageUp/PageDown skip ~10. These go through
  // MvLabApp (folder_model_mac + browse_index), not an input_snapshot seq --
  // navigation is "load this specific path next," a one-shot command, not
  // per-frame render-thread state the way pan/zoom/mouse are.
  if (c == NSLeftArrowFunctionKey || c == 'a' || c == 'A') {
    [self.app navigatePrev];
    return;
  }
  if (c == NSRightArrowFunctionKey || c == 'd' || c == 'D') {
    [self.app navigateNext];
    return;
  }
  if (c == NSHomeFunctionKey) {
    [self.app navigateFirst];
    return;
  }
  if (c == NSEndFunctionKey) {
    [self.app navigateLast];
    return;
  }
  if (c == NSPageUpFunctionKey) {
    [self.app navigateSkip:-10];
    return;
  }
  if (c == NSPageDownFunctionKey) {
    [self.app navigateSkip:10];
    return;
  }
  // The physical key labelled "delete" on a Mac keyboard sends 0x7F (what
  // AppKit calls NSDeleteCharacter) and sits where a PC's Backspace does --
  // plan/16 pairs this with Space as previous/next. A PC-style separate
  // forward-delete (fn+Delete, NSDeleteFunctionKey on the keys that have
  // one) is left unbound here on purpose: plan/16's actual `Delete` command
  // (Trash, with confirm) is follow-up work, and reusing this same key for
  // it would collide with "previous" the moment it lands -- whoever wires
  // Trash needs to pick a different binding or revisit this one.
  if (c == NSDeleteCharacter && self.app && [self.app hasFolder]) {
    [self.app navigatePrev];
    return;
  }

  if (c == NSF3FunctionKey || c == 'f' || c == 'F') {
    ++self.snap->toggle_overlay_seq;
  } else if (c == ' ') {
    // Space is the lab's own sweep-bar toggle only when no folder is open
    // (plain `mediaviewer_lab --soak N`, the PR 16 present-loop instrument).
    // Once a folder is open, plan/16 is explicit: "Space is not the lab
    // sweep after PR 6" -- it becomes next.
    if (self.app && [self.app hasFolder]) {
      [self.app navigateNext];
      return;
    }
    ++self.snap->toggle_animation_seq;
  } else if (c == 'r' || c == 'R') {
    ++self.snap->reset_stats_seq;
  } else if (c == '0') {
    ++self.snap->fit_seq;
  } else if (c == '1') {
    ++self.snap->one_to_one_seq;
  } else if (c == 0x1b) {
    [self.window close];
    return;
  }
  ++self.snap->activity_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}
@end

@implementation MvLabApp {
  mv::shell::present_lab_mac _lab;
  mv::shell::input_snapshot _snap;
  mv::job_system _jobs;
  mv::shell::mac_lab_options _options;
  bool _terminating;

  // Folder navigation (PR 18, folded-in PR 4/6 -- plan/12 2026-09-17).
  // `_items`/`_index` are a cache: refreshed only when -refreshFolderIfChanged
  // sees folder_model_mac's watch fire, not re-fetched on every keypress --
  // plan/16's own speed rule ("warm arrow-key < 40 ms... no marshalling hop
  // per key-repeat") is why this isn't just `_folder.items()` called from
  // -navigateNext etc, which would copy the whole listing (paths and all)
  // on every arrow key.
  mv::shell::folder_model _folder;
  mv::shell::browse_index _index;
  std::vector<mv::io::dir_entry> _items;
  // The path -selectIndex: last asked to display. Anchors the selection
  // across a relist: found again -> that's the new index (files added
  // elsewhere in the folder don't move the selection); not found (removed)
  // -> falls back to clamping the old numeric index, which is "the next one
  // slides into its place" for a mid-list removal and "the previous one" for
  // the last item, without needing to special-case either (plan/16).
  std::string _wantSelectedPath;
  NSTimer* _folderPollTimer;
}
- (instancetype)initWithOptions:(const mv::shell::mac_lab_options&)options {
  self = [super init];
  if (self) _options = options;
  return self;
}
- (void)applicationDidFinishLaunching:(NSNotification*)notification {
  (void)notification;
  NSRect rect = NSMakeRect(0, 0, 1280, 720);
  self.window = [[NSWindow alloc]
      initWithContentRect:rect
                styleMask:NSWindowStyleMaskTitled | NSWindowStyleMaskClosable |
                          NSWindowStyleMaskMiniaturizable | NSWindowStyleMaskResizable
                  backing:NSBackingStoreBuffered
                    defer:NO];
  self.window.title = @"MediaViewer present lab";
  self.window.delegate = self;
  [self.window center];

  // PR 18: contentView becomes a plain container holding two siblings — the
  // Metal canvas (full bounds, unchanged from PR 16/17) and the SwiftUI
  // command bar pinned to the top strip, drawn over the canvas's top pixels.
  // Neither view is resized to make room for the other; syncSize keeps
  // publishing the canvas's own full backing size, and chrome_height_px
  // tells the render thread how much of it the bar visually covers.
  NSView* container = [[NSView alloc] initWithFrame:rect];
  self.window.contentView = container;

  self.view = [[MvMetalView alloc] initWithFrame:container.bounds];
  self.view.autoresizingMask = NSViewWidthSizable | NSViewHeightSizable;
  self.view.lab = &_lab;
  self.view.snap = &_snap;
  self.view.app = self;
  [container addSubview:self.view];

  self.commandBar = [MVChromeHost makeCommandBarView];
  [container addSubview:self.commandBar];
  [NSLayoutConstraint activateConstraints:@[
    [self.commandBar.leadingAnchor constraintEqualToAnchor:container.leadingAnchor],
    [self.commandBar.trailingAnchor constraintEqualToAnchor:container.trailingAnchor],
    [self.commandBar.topAnchor constraintEqualToAnchor:container.topAnchor],
    [self.commandBar.heightAnchor constraintEqualToConstant:kChromeBarHeightPoints],
  ]];

  g_chrome_snap = &_snap;
  g_chrome_lab = &_lab;

  _snap.window_visible = YES;
  _snap.window_active = YES;
  [self.view syncSize];

  if (auto started = _jobs.start(); !mv::ok(started)) {
    MV_LOG_ERROR("job_system failed to start");
    [NSApp terminate:nil];
    return;
  }
  _options.jobs = &_jobs;
  if (auto started = _lab.start((__bridge void*)self.view, _options); !started) {
    MV_LOG_ERROR("present lab failed to start");
    [NSApp terminate:nil];
    return;
  }

  // plan/16 "Opening (argv, drop, PR 6)": --open (or a bare positional path,
  // parsed into the same options_.open_path below) resolves through the same
  // folder+select rule a drop does, now that folder_model_mac exists to
  // resolve it -- not a direct one-off open_item() with no folder context.
  if (!_options.open_path.empty() && ![self openEntryPath:_options.open_path.c_str()]) {
    NSBeep();
  }

  // folder_model_mac's relist/thumb watch fires on its own FSEvents thread
  // (io/dir.h: "must not block and must not re-enter the watcher" -- it
  // just flips an atomic). Polling consume_changed() on a UI-thread timer,
  // rather than doing real work from that callback, is what keeps this
  // rule intact while still picking up "a file dropped into the folder
  // appears without restart" (plan/10-roadmap.md PR 4's verify line).
  _folderPollTimer = [NSTimer scheduledTimerWithTimeInterval:0.2
                                                       target:self
                                                     selector:@selector(refreshFolderIfChanged)
                                                     userInfo:nil
                                                      repeats:YES];

  [self.window makeKeyAndOrderFront:nil];
  [NSApp activateIgnoringOtherApps:YES];
}

- (BOOL)hasFolder {
  return !_items.empty();
}

- (BOOL)openEntryPath:(const char*)utf8_path {
  if (!utf8_path || !*utf8_path) return NO;
  const std::string path(utf8_path);
  // A single stat() to answer "does anything exist here" is the one I/O
  // this method does inline -- cheap and synchronous by nature, the same
  // exception every "no I/O on the UI thread" codebase makes for a stat
  // call, unlike the real I/O folder_model::open() below does.
  auto is_dir = mv::io::is_directory(path);
  if (!is_dir) return NO;  // stat failed: nothing exists at this path

  std::string dir;
  std::string select_path;
  if (is_dir.value()) {
    dir = path;
  } else {
    auto containing = mv::io::containing_dir(path);
    if (!containing) return NO;
    dir = containing.value();
    select_path = path;
  }

  // The listing itself is already async (folder_model_mac::relist_async
  // submits its own job); -refreshFolderIfChanged picks it up once
  // consume_changed() fires and resolves `_wantSelectedPath` against the
  // real listing. Resetting `_index`/`_items` now, synchronously (no I/O
  // here, just clearing C++ containers), means a relist that lands for a
  // *different* folder in flight can never be mistaken for this one's.
  _wantSelectedPath = select_path;
  _items.clear();
  _index.reset(0);

  // folder_model::open() itself is real I/O -- opening, and maybe creating,
  // the thumbnail cache's SQLite file -- so it never runs on the UI thread
  // (CLAUDE.md rule 1: "no I/O"), unlike the is_directory() stat above.
  // `&_folder`/`&_jobs` stay valid for the job's duration because MvLabApp
  // is never destroyed before the process exits -- unlike folder_model_mac's
  // own internal jobs, which capture a shared_ptr<shared_state> precisely
  // because a folder_model *can* be destroyed mid-job in general.
  mv::shell::folder_model* folder = &_folder;
  mv::job_system* jobs = &_jobs;
  _jobs.submit_at(mv::background_generation,
                  [folder, jobs, dir](const mv::job_context&) -> mv::status {
                    auto opened = folder->open(dir, *jobs);
                    if (!opened) {
                      dispatch_async(dispatch_get_main_queue(), ^{
                        NSBeep();
                      });
                      return opened.error();
                    }
                    return mv::status::ok;
                  });
  return YES;
}

- (void)refreshFolderIfChanged {
  if (!_folder.consume_changed()) return;
  _items = _folder.items();

  std::size_t new_index = 0;
  if (!_items.empty()) {
    bool found = false;
    if (!_wantSelectedPath.empty()) {
      for (std::size_t i = 0; i < _items.size(); ++i) {
        if (_items[i].path_utf8 == _wantSelectedPath) {
          new_index = i;
          found = true;
          break;
        }
      }
    }
    if (!found) {
      new_index = std::min(_index.current(), _items.size() - 1);
    }
  }
  [self selectIndex:new_index];
}

- (void)selectIndex:(std::size_t)new_index {
  _index.reset(_items.size(), new_index);

  if (_items.empty()) {
    _wantSelectedPath.clear();
    _snap.item_index = 0;
    _snap.item_count = 0;
    _snap.item_name[0] = '\0';
  } else {
    const mv::io::dir_entry& entry = _items[_index.current()];
    _wantSelectedPath = entry.path_utf8;
    _lab.open_item(entry.path_utf8);
    _snap.item_index = static_cast<std::uint32_t>(_index.current());
    _snap.item_count = static_cast<std::uint32_t>(_items.size());
    const std::size_t n = std::min(entry.name_utf8.size(), sizeof(_snap.item_name) - 1);
    std::memcpy(_snap.item_name, entry.name_utf8.data(), n);
    _snap.item_name[n] = '\0';
  }

  ++_snap.activity_seq;
  [self.view publish];
  _lab.wake();
}

- (void)navigateNext {
  if (_items.empty()) return;
  [self selectIndex:_index.next()];
}
- (void)navigatePrev {
  if (_items.empty()) return;
  [self selectIndex:_index.prev()];
}
- (void)navigateFirst {
  if (_items.empty()) return;
  [self selectIndex:_index.first()];
}
- (void)navigateLast {
  if (_items.empty()) return;
  [self selectIndex:_index.last()];
}
- (void)navigateSkip:(std::ptrdiff_t)delta {
  if (_items.empty()) return;
  [self selectIndex:_index.skip(delta)];
}
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(NSApplication*)sender {
  (void)sender;
  return YES;
}
- (void)windowWillClose:(NSNotification*)notification {
  (void)notification;
  // Command-bar buttons stop reaching the lab first: they only poke _snap
  // through the g_chrome_* globals, so clearing those before teardown means
  // a button click racing window close can never touch a torn-down lab.
  // This is the only work windowWillClose does -- it runs on the main
  // thread and must not block it (CLAUDE.md rule 1). The actual teardown
  // (job_system::shutdown() joining workers, _lab.stop() joining the render
  // thread) can take as long as an in-flight decode+upload job does, so it
  // runs off the main thread in -applicationShouldTerminate: instead, which
  // fires only after the window has already closed.
  g_chrome_snap = nullptr;
  g_chrome_lab = nullptr;
  [_folderPollTimer invalidate];
  _folderPollTimer = nil;
  // Stops and joins the FSEvents watch thread; safe on the main thread per
  // io/dir.h's contract, and cheap -- in-flight relist/thumb jobs keep their
  // own shared_ptr<shared_state> and finish safely regardless (folder_model_mac.h).
  _folder.close();
}
- (NSApplicationTerminateReply)applicationShouldTerminate:(NSApplication*)sender {
  (void)sender;
  if (_terminating) return NSTerminateLater;
  _terminating = true;
  // Jobs first: submit_image_load()'s job holds a raw (non-retaining)
  // id<MTLDevice> pointer, so it must finish before _lab.stop() reaches
  // device_.destroy() on the render thread -- shutdown() drains queued jobs
  // and joins running ones, so this ordering guarantees that. Both block,
  // so both run on a background queue; the window is already closed by the
  // time this method runs, so nothing user-visible waits on it.
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    _jobs.shutdown();
    _lab.stop();
    dispatch_async(dispatch_get_main_queue(), ^{
      [NSApp replyToApplicationShouldTerminate:YES];
    });
  });
  return NSTerminateLater;
}
- (void)windowDidChangeOcclusionState:(NSNotification*)notification {
  (void)notification;
  _snap.window_visible = (self.window.occlusionState & NSWindowOcclusionStateVisible) != 0;
  [self.view publish];
  _lab.wake();
}
- (void)windowDidBecomeKey:(NSNotification*)notification {
  (void)notification;
  _snap.window_active = true;
  [self.view publish];
}
- (void)windowDidResignKey:(NSNotification*)notification {
  (void)notification;
  _snap.window_active = false;
  [self.view publish];
}
- (int)exitCode {
  return _lab.exit_code();
}
@end

namespace {

void usage() {
  std::fprintf(stderr,
               "mediaviewer_lab — Metal present lab (PR 16), still decode + pan/zoom (PR 17),\n"
               "                  folder browse + drag-drop (PR 18)\n"
               "  --soak N --json PATH [--gate] [--static] [--no-overlay]\n"
               "  --open PATH   or a bare PATH: a folder opens that folder; a file opens its\n"
               "                folder with that file selected (plan/16-commands.md). Wheel to\n"
               "                zoom toward the cursor, drag to pan, 0 fit, 1 one-to-one.\n"
               "                Left/Right or A/D previous/next, Home/End first/last,\n"
               "                PageUp/PageDown skip ~10, Space next once a folder is open.\n");
}

}  // namespace

int main(int argc, char** argv) {
  mv::trace::provider_register();
  mv::shell::mac_lab_options options;
  for (int i = 1; i < argc; ++i) {
    const char* arg = argv[i];
    auto next = [&]() -> const char* { return i + 1 < argc ? argv[++i] : ""; };
    if (std::strcmp(arg, "--soak") == 0) {
      options.soak_seconds = std::strtod(next(), nullptr);
    } else if (std::strcmp(arg, "--json") == 0) {
      options.json_report_path = next();
    } else if (std::strcmp(arg, "--gate") == 0) {
      options.gate_exit_code = true;
    } else if (std::strcmp(arg, "--static") == 0) {
      options.start_animating = false;
    } else if (std::strcmp(arg, "--no-overlay") == 0) {
      options.overlay_visible = false;
    } else if (std::strcmp(arg, "--open") == 0) {
      options.open_path = next();
    } else if (std::strcmp(arg, "--help") == 0 || std::strcmp(arg, "-h") == 0) {
      usage();
      return 0;
    } else if (arg[0] != '-') {
      // A bare positional path: "the first entry that exists wins"
      // (plan/16-commands.md) -- MvLabApp resolves it (folder, or a file's
      // containing folder with that file selected) after the lab starts.
      // The first one given wins if more than one is passed; later ones are
      // ignored rather than erroring, matching a drop of several files.
      if (options.open_path.empty()) options.open_path = arg;
    } else {
      std::fprintf(stderr, "mediaviewer_lab: unrecognised argument %s\n", arg);
      usage();
      return 2;
    }
  }
  if (options.soak_seconds > 0.0) {
    bool saw_static = false;
    for (int i = 1; i < argc; ++i) {
      if (std::strcmp(argv[i], "--static") == 0) saw_static = true;
    }
    options.start_animating = !saw_static;
  }

  @autoreleasepool {
    [NSApplication sharedApplication];
    [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];
    MvLabApp* app = [[MvLabApp alloc] initWithOptions:options];
    NSApp.delegate = app;
    [NSApp run];
    const int code = [app exitCode];
    mv::trace::provider_unregister();
    return code;
  }
}
