// SPDX-License-Identifier: GPL-2.0-or-later
// AppKit host for the Metal present lab. PR 16/17 built the canvas; PR 18
// adds the SwiftUI command bar hosted alongside it (plan/10, plan/15 —
// "the canvas is not ported to SwiftUI"). MvMetalView keeps covering the
// whole content view, exactly as PR 16/17 built it; the command bar is a
// sibling NSView drawn on top of its own top strip, the same "swapchain
// spans the client area, chrome is composited over it" shape the Windows
// DComp islands use — not a resize of the Metal view.
#import <AppKit/AppKit.h>
#import <Metal/Metal.h>
#import <QuartzCore/CAMetalLayer.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>

#include "core/job_system.h"
#include "core/trace.h"
#include "shell/input_state.h"
#include "shell/present_lab_mac.h"

// Generated by swiftc -emit-objc-header from src.swift/MediaViewerChrome
// (cmake/darwin.cmake builds that target before this file, and adds its
// output directory to the include path). Declares `MVChromeHost` /
// `+makeCommandBarView`, the one thing this file needs from Swift — see
// src.swift/MediaViewerChrome/Sources/MediaViewerChrome/ChromeHost.swift.
#import "MediaViewerChrome-Swift.h"

namespace {
// Bridge target for mv_chrome_fit()/mv_chrome_one_to_one() (declared in
// src.swift/MediaViewerChrome/Sources/MVChromeBridge, called from
// CommandBarView.swift). Set once in -applicationDidFinishLaunching:, same
// lifetime as the window; the lab and its snapshot outlive the app delegate
// only because both are ivars of the single MvLabApp instance that owns this
// process's only window (plan/14-abi.md's shape, scoped to the lab).
mv::shell::input_snapshot* g_chrome_snap = nullptr;
mv::shell::present_lab_mac* g_chrome_lab = nullptr;
}  // namespace

// [any-thread] SwiftUI runs button actions on the main actor, so these run
// on the main thread in practice; they only ever touch input_snapshot the
// same way MvMetalView's event handlers do (edge-triggered counter bump,
// then wake), so there is nothing here that requires it.
extern "C" void mv_chrome_fit(void) {
  if (!g_chrome_snap) return;
  ++g_chrome_snap->fit_seq;
  if (g_chrome_lab) g_chrome_lab->wake();
}
extern "C" void mv_chrome_one_to_one(void) {
  if (!g_chrome_snap) return;
  ++g_chrome_snap->one_to_one_seq;
  if (g_chrome_lab) g_chrome_lab->wake();
}

// Command-bar strip height, in points (converted to backing pixels via the
// window's backingScaleFactor before it reaches input_snapshot.chrome_height_px
// — that field, and every canvas-rect field alongside it, is already in
// physical pixels, matching Windows' PerMonitorV2 convention).
constexpr CGFloat kChromeBarHeightPoints = 44.0;

@interface MvMetalView : NSView
@property(nonatomic, assign) mv::shell::present_lab_mac* lab;
@property(nonatomic, assign) mv::shell::input_snapshot* snap;
@end

@implementation MvMetalView
- (BOOL)wantsLayer {
  return YES;
}
- (CALayer*)makeBackingLayer {
  CAMetalLayer* layer = [CAMetalLayer layer];
  layer.pixelFormat = MTLPixelFormatBGRA8Unorm_sRGB;
  layer.framebufferOnly = YES;
  layer.maximumDrawableCount = 1;
  layer.displaySyncEnabled = YES;
  return layer;
}
- (BOOL)acceptsFirstResponder {
  return YES;
}
- (BOOL)isOpaque {
  return YES;
}

- (void)publish {
  if (self.lab && self.snap) self.lab->publish(*self.snap);
}

- (void)syncSize {
  const NSSize backing = [self convertSizeToBacking:self.bounds.size];
  self.snap->width = static_cast<std::uint32_t>(std::max(1.0, backing.width));
  self.snap->height = static_cast<std::uint32_t>(std::max(1.0, backing.height));
  self.snap->dpi_scale = static_cast<float>(self.window.backingScaleFactor);
  self.snap->chrome_height_px = static_cast<std::uint32_t>(
      kChromeBarHeightPoints * self.window.backingScaleFactor);
  ++self.snap->resize_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}

- (void)viewDidMoveToWindow {
  [super viewDidMoveToWindow];
  [self syncSize];
}

- (void)setFrameSize:(NSSize)newSize {
  [super setFrameSize:newSize];
  [self syncSize];
}

- (void)viewDidChangeBackingProperties {
  [super viewDidChangeBackingProperties];
  ++self.snap->display_change_seq;
  [self syncSize];
}

- (void)mouseDown:(NSEvent*)event {
  (void)event;
  self.snap->mouse_down[0] = true;
  ++self.snap->activity_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}
- (void)mouseUp:(NSEvent*)event {
  (void)event;
  self.snap->mouse_down[0] = false;
  ++self.snap->activity_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}
- (void)rightMouseDown:(NSEvent*)event {
  (void)event;
  self.snap->mouse_down[1] = true;
  ++self.snap->activity_seq;
  [self publish];
}
- (void)rightMouseUp:(NSEvent*)event {
  (void)event;
  self.snap->mouse_down[1] = false;
  [self publish];
}
- (void)scrollWheel:(NSEvent*)event {
  self.snap->wheel_total += static_cast<std::int64_t>(event.scrollingDeltaY * 120.0);
  ++self.snap->activity_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}
- (void)mouseMoved:(NSEvent*)event {
  const NSPoint p = [self convertPoint:event.locationInWindow fromView:nil];
  const NSPoint backing = [self convertPointToBacking:p];
  self.snap->mouse_x = static_cast<float>(backing.x);
  self.snap->mouse_y = static_cast<float>(self.snap->height) - static_cast<float>(backing.y);
  self.snap->mouse_in_client = NSPointInRect(p, self.bounds);
  [self publish];
}
- (void)mouseDragged:(NSEvent*)event {
  [self mouseMoved:event];
  ++self.snap->activity_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}
- (void)keyDown:(NSEvent*)event {
  const NSString* chars = event.charactersIgnoringModifiers;
  const unichar c = chars.length > 0 ? [chars characterAtIndex:0] : 0;
  if (c == NSF3FunctionKey || c == 'f' || c == 'F') {
    ++self.snap->toggle_overlay_seq;
  } else if (c == ' ') {
    ++self.snap->toggle_animation_seq;
  } else if (c == 'r' || c == 'R') {
    ++self.snap->reset_stats_seq;
  } else if (c == '0') {
    ++self.snap->fit_seq;
  } else if (c == '1') {
    ++self.snap->one_to_one_seq;
  } else if (c == 0x1b) {
    [self.window close];
    return;
  }
  ++self.snap->activity_seq;
  [self publish];
  if (self.lab) self.lab->wake();
}
@end

@interface MvLabApp : NSObject <NSApplicationDelegate, NSWindowDelegate>
@property(nonatomic, strong) NSWindow* window;
@property(nonatomic, strong) MvMetalView* view;
@property(nonatomic, strong) NSView* commandBar;
@end

@implementation MvLabApp {
  mv::shell::present_lab_mac _lab;
  mv::shell::input_snapshot _snap;
  mv::job_system _jobs;
  mv::shell::mac_lab_options _options;
  bool _terminating;
}
- (instancetype)initWithOptions:(const mv::shell::mac_lab_options&)options {
  self = [super init];
  if (self) _options = options;
  return self;
}
- (void)applicationDidFinishLaunching:(NSNotification*)notification {
  (void)notification;
  NSRect rect = NSMakeRect(0, 0, 1280, 720);
  self.window = [[NSWindow alloc]
      initWithContentRect:rect
                styleMask:NSWindowStyleMaskTitled | NSWindowStyleMaskClosable |
                          NSWindowStyleMaskMiniaturizable | NSWindowStyleMaskResizable
                  backing:NSBackingStoreBuffered
                    defer:NO];
  self.window.title = @"MediaViewer present lab";
  self.window.delegate = self;
  [self.window center];

  // PR 18: contentView becomes a plain container holding two siblings — the
  // Metal canvas (full bounds, unchanged from PR 16/17) and the SwiftUI
  // command bar pinned to the top strip, drawn over the canvas's top pixels.
  // Neither view is resized to make room for the other; syncSize keeps
  // publishing the canvas's own full backing size, and chrome_height_px
  // tells the render thread how much of it the bar visually covers.
  NSView* container = [[NSView alloc] initWithFrame:rect];
  self.window.contentView = container;

  self.view = [[MvMetalView alloc] initWithFrame:container.bounds];
  self.view.autoresizingMask = NSViewWidthSizable | NSViewHeightSizable;
  self.view.lab = &_lab;
  self.view.snap = &_snap;
  [container addSubview:self.view];

  self.commandBar = [MVChromeHost makeCommandBarView];
  [container addSubview:self.commandBar];
  [NSLayoutConstraint activateConstraints:@[
    [self.commandBar.leadingAnchor constraintEqualToAnchor:container.leadingAnchor],
    [self.commandBar.trailingAnchor constraintEqualToAnchor:container.trailingAnchor],
    [self.commandBar.topAnchor constraintEqualToAnchor:container.topAnchor],
    [self.commandBar.heightAnchor constraintEqualToConstant:kChromeBarHeightPoints],
  ]];

  g_chrome_snap = &_snap;
  g_chrome_lab = &_lab;

  _snap.window_visible = YES;
  _snap.window_active = YES;
  [self.view syncSize];

  if (auto started = _jobs.start(); !mv::ok(started)) {
    MV_LOG_ERROR("job_system failed to start");
    [NSApp terminate:nil];
    return;
  }
  _options.jobs = &_jobs;
  if (auto started = _lab.start((__bridge void*)self.view, _options); !started) {
    MV_LOG_ERROR("present lab failed to start");
    [NSApp terminate:nil];
    return;
  }
  [self.window makeKeyAndOrderFront:nil];
  [NSApp activateIgnoringOtherApps:YES];
}
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(NSApplication*)sender {
  (void)sender;
  return YES;
}
- (void)windowWillClose:(NSNotification*)notification {
  (void)notification;
  // Command-bar buttons stop reaching the lab first: they only poke _snap
  // through the g_chrome_* globals, so clearing those before teardown means
  // a button click racing window close can never touch a torn-down lab.
  // This is the only work windowWillClose does -- it runs on the main
  // thread and must not block it (CLAUDE.md rule 1). The actual teardown
  // (job_system::shutdown() joining workers, _lab.stop() joining the render
  // thread) can take as long as an in-flight decode+upload job does, so it
  // runs off the main thread in -applicationShouldTerminate: instead, which
  // fires only after the window has already closed.
  g_chrome_snap = nullptr;
  g_chrome_lab = nullptr;
}
- (NSApplicationTerminateReply)applicationShouldTerminate:(NSApplication*)sender {
  (void)sender;
  if (_terminating) return NSTerminateLater;
  _terminating = true;
  // Jobs first: submit_image_load()'s job holds a raw (non-retaining)
  // id<MTLDevice> pointer, so it must finish before _lab.stop() reaches
  // device_.destroy() on the render thread -- shutdown() drains queued jobs
  // and joins running ones, so this ordering guarantees that. Both block,
  // so both run on a background queue; the window is already closed by the
  // time this method runs, so nothing user-visible waits on it.
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    _jobs.shutdown();
    _lab.stop();
    dispatch_async(dispatch_get_main_queue(), ^{
      [NSApp replyToApplicationShouldTerminate:YES];
    });
  });
  return NSTerminateLater;
}
- (void)windowDidChangeOcclusionState:(NSNotification*)notification {
  (void)notification;
  _snap.window_visible = (self.window.occlusionState & NSWindowOcclusionStateVisible) != 0;
  [self.view publish];
  _lab.wake();
}
- (void)windowDidBecomeKey:(NSNotification*)notification {
  (void)notification;
  _snap.window_active = true;
  [self.view publish];
}
- (void)windowDidResignKey:(NSNotification*)notification {
  (void)notification;
  _snap.window_active = false;
  [self.view publish];
}
- (int)exitCode {
  return _lab.exit_code();
}
@end

namespace {

void usage() {
  std::fprintf(stderr,
               "mediaviewer_lab — Metal present lab (PR 16), still decode + pan/zoom (PR 17)\n"
               "  --soak N --json PATH [--gate] [--static] [--no-overlay]\n"
               "  --open PATH   decode a JPEG/PNG/BMP and fit it; wheel to zoom toward the\n"
               "                cursor, drag to pan, 0 fit, 1 one-to-one\n");
}

}  // namespace

int main(int argc, char** argv) {
  mv::trace::provider_register();
  mv::shell::mac_lab_options options;
  for (int i = 1; i < argc; ++i) {
    const char* arg = argv[i];
    auto next = [&]() -> const char* { return i + 1 < argc ? argv[++i] : ""; };
    if (std::strcmp(arg, "--soak") == 0) {
      options.soak_seconds = std::strtod(next(), nullptr);
    } else if (std::strcmp(arg, "--json") == 0) {
      options.json_report_path = next();
    } else if (std::strcmp(arg, "--gate") == 0) {
      options.gate_exit_code = true;
    } else if (std::strcmp(arg, "--static") == 0) {
      options.start_animating = false;
    } else if (std::strcmp(arg, "--no-overlay") == 0) {
      options.overlay_visible = false;
    } else if (std::strcmp(arg, "--open") == 0) {
      options.open_path = next();
    } else if (std::strcmp(arg, "--help") == 0 || std::strcmp(arg, "-h") == 0) {
      usage();
      return 0;
    } else {
      std::fprintf(stderr, "mediaviewer_lab: unrecognised argument %s\n", arg);
      usage();
      return 2;
    }
  }
  if (options.soak_seconds > 0.0) {
    bool saw_static = false;
    for (int i = 1; i < argc; ++i) {
      if (std::strcmp(argv[i], "--static") == 0) saw_static = true;
    }
    options.start_animating = !saw_static;
  }

  @autoreleasepool {
    [NSApplication sharedApplication];
    [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];
    MvLabApp* app = [[MvLabApp alloc] initWithOptions:options];
    NSApp.delegate = app;
    [NSApp run];
    const int code = [app exitCode];
    mv::trace::provider_unregister();
    return code;
  }
}
